apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gke-abc-auth-deployment
  namespace: default
  labels:
    app: gke-abc-auth-deployment
spec:
  replicas: 1 # number of pods
  template:
    metadata:
      labels:
        app: gke-abc-auth-deployment
    spec:
      containers:
        - name: gke-abc-auth-image
          image: gcr.io/phrasal-waters-350317/gke-abc-auth-image
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
