apiVersion: v1
kind: Service
metadata:
  name: abc-auth-app-service
  namespace: default
spec:
  selector:
    app: abc-auth-app-service
  ports:
    - name: abc-auth-app-service
      protocol: TCP
      port: 4501
      targetPort: 4500
