apiVersion: v1
kind: Service
metadata:
  name: ctse-product-service
spec:
  type: NodePort
  selector:
    app: ctse-product-deployment
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4000
