name: Docker Build Deploy Authentication

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-authentication

    steps:
      - uses: actions/checkout@v3
      - name : run shell script
        run: echo commit hash is ${{ github.sha }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.SHALITHA_DOCKER_USERNAME }}
          password: ${{ secrets.SHALITHA_DOCKER_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.SHALITHA_DOCKER_USERNAME }}/abc-authentication:${{ github.sha }}
