name: Docker Build Deploy Sales Management

on:
  push:
    branches: [ feature/order_management ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name : run shell script
        run: echo commit hash is ${{ github.sha }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.SASINDU_DOCKER_USERNAME }}
          password: ${{ secrets.SASINDU_DOCKER_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./api-sales/Dockerfile
          push: true
          tags: ${{ secrets.SASINDU_DOCKER_USERNAME }}/abc-salesmanagement:${{ github.sha }}
